# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainwindow(object):
    def setupUi(self, mainwindow):
        mainwindow.setObjectName("mainwindow")
        mainwindow.resize(942, 679)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainwindow.sizePolicy().hasHeightForWidth())
        mainwindow.setSizePolicy(sizePolicy)
        mainwindow.setToolTipDuration(0)
        mainwindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphbtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphbtn.sizePolicy().hasHeightForWidth())
        self.graphbtn.setSizePolicy(sizePolicy)
        self.graphbtn.setObjectName("graphbtn")
        self.gridLayout_2.addWidget(self.graphbtn, 4, 0, 1, 3)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoScroll(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 3, 0, 1, 1)
        self.titlebox = QtWidgets.QLineEdit(self.centralwidget)
        self.titlebox.setObjectName("titlebox")
        self.gridLayout_2.addWidget(self.titlebox, 2, 0, 1, 1)
        self.openFile = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFile.sizePolicy().hasHeightForWidth())
        self.openFile.setSizePolicy(sizePolicy)
        self.openFile.setObjectName("openFile")
        self.gridLayout_2.addWidget(self.openFile, 0, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(676, 0))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.dataTable = QtWidgets.QCheckBox(self.groupBox)
        self.dataTable.setObjectName("dataTable")
        self.gridLayout.addWidget(self.dataTable, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 13, 0, 1, 1)
        self.current = QtWidgets.QCheckBox(self.groupBox)
        self.current.setObjectName("current")
        self.gridLayout.addWidget(self.current, 8, 0, 1, 1)
        self.voltage = QtWidgets.QCheckBox(self.groupBox)
        self.voltage.setObjectName("voltage")
        self.gridLayout.addWidget(self.voltage, 10, 0, 1, 1)
        self.filterBox = QtWidgets.QComboBox(self.groupBox)
        self.filterBox.setObjectName("filterBox")
        self.gridLayout.addWidget(self.filterBox, 3, 0, 1, 1)
        self.average = QtWidgets.QCheckBox(self.groupBox)
        self.average.setObjectName("average")
        self.gridLayout.addWidget(self.average, 12, 0, 1, 1)
        self.accelvtime = QtWidgets.QCheckBox(self.groupBox)
        self.accelvtime.setObjectName("accelvtime")
        self.gridLayout.addWidget(self.accelvtime, 7, 0, 1, 1)
        self.accelvdisp = QtWidgets.QCheckBox(self.groupBox)
        self.accelvdisp.setObjectName("accelvdisp")
        self.gridLayout.addWidget(self.accelvdisp, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 2, 1, 1)
        mainwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainwindow)
        self.statusbar.setObjectName("statusbar")
        mainwindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainwindow)
        QtCore.QMetaObject.connectSlotsByName(mainwindow)

    def retranslateUi(self, mainwindow):
        _translate = QtCore.QCoreApplication.translate
        mainwindow.setWindowTitle(_translate("mainwindow", "Test Bay Analyzer"))
        self.graphbtn.setText(_translate("mainwindow", "Start"))
        self.openFile.setText(_translate("mainwindow", "Select Directory"))
        self.label_2.setText(_translate("mainwindow", "Title"))
        self.groupBox.setTitle(_translate("mainwindow", "Selection Box"))
        self.dataTable.setText(_translate("mainwindow", "Data Table"))
        self.label_3.setText(_translate("mainwindow", "Selecting Average will only take averages of Acceleration vs. Displacement and Acceleration vs. Time"))
        self.current.setText(_translate("mainwindow", "Current"))
        self.voltage.setText(_translate("mainwindow", "Voltage"))
        self.average.setText(_translate("mainwindow", "Average"))
        self.accelvtime.setText(_translate("mainwindow", "Acceleration vs. Time"))
        self.accelvdisp.setText(_translate("mainwindow", "Acceleration vs. Displacement"))
        self.label.setText(_translate("mainwindow", "Filtering"))

